### ISSUE TITLE
NOINTERMISSION, also defining level finished music?

### ISSUE THREAD

**Issue by Chonkblonk** [kraflab/umapinfo#2]
Any chance the NOINTERMISSION thing will work whenever the next version of of UMAPINFO is rolled out? So one can skip the level score screen.

Not sure if you take suggestions here, but it'd also be very helpful to be able to define which music plays during the end level score screen.
I was also gonna say being able to define a text crawl to go before a level happens (such as the start of the episode), but I could work perfectly fine with a black box dummy level which immediately ends, assuming there was a way to skip the score screen, and it goes direct to the text crawl and then the next level.

If this is out of place, I apologize.

**Comment by kraflab** [comment]
If you have feature requests, please consider opening a separate issue for each feature, rather than grouping them all in one post. That will give better visibility and allow for more focused discussions. However, this is probably not the place to request features.

UMAPINFO is not a comprehensive solution for map info, but represents a limited expansion of features. Anything added at this point should either be totally cosmetic (e.g., the author field recently added) or fix some discrepancy in the standard itself. The problem with having a moving standard with important technical changes between versions would be that you end up in a situation where different ports that are all "umapinfo-compatible" may or may not actually work with a given umapinfo lump. It doesn't mean there can't be a major update at some point, but I wouldn't expect it any time soon.

**Comment by Chonkblonk** [comment]
Alright, thanks for your answer, and apologies for putting this in the wrong space, github is pretty foreign to me.

This feels like a cosmetic kind of thing to me, as what I was looking for was a cleaner way of doing a text crawl at the start of an episode. Thus, not a significant one, and I was hesitant to ask, but any answer is useful.

Perhaps I'll do it the inelegant way and then the cosmetic GzDoom patch will smooth it over for people playing with that port, or maybe I'll think of something else.

In any case, I thank you for your time, and I look forward to whichever future works you'll unveil, MBF21 and UMAPINFO alone have been an incredible liberation, and I'm very fond of them.
